version: '3.8'

services:
  mySQL:
    image: mysql:latest
    restart: always
    container_name: mydb
    environment:
      - MYSQL_DATABASE=tienda_online
      - MYSQL_ROOT_PASSWORD=utags2023
    ports:
      - '3306:3306'
    volumes:
      - ./tienda.sql:/docker-entrypoint-sql.d/tienda.sql
